#!/bin/bash

git clone https://github.com/bucharest-gold/s2i-nodejs.git
cd s2i-nodejs

echo "---> onbuild using centos7"
docker build --pull=false -t tests2inodejscentos7 .

echo "---> onbuild using fedora"
docker build --pull=false --file Dockerfile.fedora -t tests2inodejsfedora .

