#!/bin/bash

oc cluster up
oc login -u system:admin

echo "---> Creating s2i-nodejs build with centos7"
oc new-app bucharestgold/centos7-s2i-nodejs-candidate:7.8.0~https://github.com/bucharest-gold/s2i-nodejs.git
sleep 60
oc expose svc/s2inodejs
sleep 60
curl $(oc get routes | awk '{print $2}' | grep xip.io)
printf "\n"
echo "---> App running"

oc new-project fedora
echo "---> Creating s2i-nodejs build with fedora"
oc new-app bucharestgold/fedora-s2i-nodejs-candidate:7.8.0~https://github.com/bucharest-gold/s2i-nodejs.git
sleep 60
oc expose svc/s2inodejs
sleep 60
curl $(oc get routes | awk '{print $2}' | grep xip.io)
printf "\n"
echo "---> App running"

oc new-project atomic
echo "---> Creating s2i-nodejs build with rhel7-atomic"
oc new-app bucharestgold/rhel7-atomic-s2i-nodejs-candidate:7.8.0~https://github.com/bucharest-gold/s2i-nodejs.git
sleep 60
oc expose svc/s2inodejs
sleep 60
curl $(oc get routes | awk '{print $2}' | grep xip.io)
printf "\n"
echo "---> App running"

oc new-project rhel7
echo "---> Creating s2i-nodejs build with rhel7"
oc new-app bucharestgold/rhel7-s2i-nodejs-candidate:7.8.0~https://github.com/bucharest-gold/s2i-nodejs.git
sleep 60
oc expose svc/s2inodejs
sleep 60
curl $(oc get routes | awk '{print $2}' | grep xip.io)
printf "\n"
echo "---> App running"
